### PR TITLE
restructure dockerfile/install.sh to better re-use the cache on rebuilds

### PR DESCRIPTION
**Pull request by deads2k**
Running the "update pieces of the OS and install prereqs" and "install the current level of my product" in the same command (`install.sh` in the dockerfile makes it painful to update to new levels of the product because there's not a layer than includes all the prereqs.

Splitting https://github.com/MediaBrowser/Emby.Build/blob/master/Docker/Dockerfile#L19 into different steps in the Dockerfile will help the layers work for you.

### CODE REVIEW

**Comment by hurricanehrndz** [comment]
May , I ask why you are not using the build images themselves. PS, I will be restructuring the whole Dockerfile soon. I personally don't have any issue with using the cache and having multiple layers. Some people though within the Docker community hate and try and have the smallest layers possible.

**Comment by deads2k** [comment]
> May , I ask why you are not using the build images themselves. PS, I will be restructuring the whole Dockerfile soon. I personally don't have any issue with using the cache and having multiple layers. Some people though within the Docker community hate and try and have the smallest layers possible.

I generally don't trust docker images built by someone else, especially when the original layers are so old (phusion is pinned to a level from January).  I couldn't see what it was doing until I pulled the Dockerfile and then it turned out that I couldn't see what it was doing until I dug into `install.sh`.  It really hurts inspectability.

I've found easiest way to keep myself up to date is ripple changes from base images through their dependencies, so I'm probably going to have my personal version of this anyway.  I just thought I'd help with the inspectability and layer re-use for anyone else vetting the image.

**Comment by deads2k** [comment]
> May , I ask why you are not using the build images themselves.

Also, working on OpenShift and Kubernetes, I like to keep up with what people are trying to do with their Dockerfiles and images.

**Comment by hurricanehrndz** [comment]
We will be restructuring the dockerfile soon.

**Pull request closed without merging**
